<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Do You Love Me?</title>
  <style>
    body {
      font-family: 'Comic Sans MS', cursive, sans-serif;
      background-color: pink;
      text-align: center;
      padding-top: 100px;
    }
    #popup {
      background: white;
      border-radius: 10px;
      padding: 40px;
      box-shadow: 0 0 15px rgba(0,0,0,0.3);
      display: inline-block;
    }
    button {
      margin: 10px;
      padding: 10px 20px;
      font-size: 18px;
      cursor: pointer;
    }
    #noBtn {
      position: absolute;
    }
  </style>
</head>
<body>
  <div id="popup">
    <h1>Do you love me?</h1>
    <button onclick="yesClicked()">Yes</button>
    <button id="noBtn" onmouseover="moveNo()">No</button>
  </div>

  <script>
    function yesClicked() {
      alert("Yay! I love you too ❤️");
    }

    function moveNo() {
      const btn = document.getElementById('noBtn');
      const x = Math.random() * (window.innerWidth - 100);
      const y = Math.random() * (window.innerHeight - 100);
      btn.style.left = `${x}px`;
      btn.style.top = `${y}px`;
    }
  </script>
</body>
</html>
